### PR TITLE
Filter viewpoint uri

### PR DESCRIPTION
**Pull request by bmaggi**
- add the generated java profile 
- set a nice uri
  => filter the viewpoint by profile application

### CODE REVIEW

**Comment by patnan** [comment]
It seems (at least for me) that this one introduced some errors. When I try to create a node from the palette i get the following exception:

Caused by: java.lang.IllegalArgumentException: org.eclipse.uml2.uml.internal.impl.StereotypeImpl@1c505d76 (name: WorkPart, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)
    at org.eclipse.uml2.uml.internal.operations.ElementOperations.setValue(ElementOperations.java:666)
    at org.eclipse.uml2.uml.internal.impl.ElementImpl.setValue(ElementImpl.java:307)
    at org.eclipse.papyrus.tutorial.anatomy.types.advices.BugzillaAdvice$1.doExecuteWithResult(BugzillaAdvice.java:28)
    at org.eclipse.gmf.runtime.emf.commands.core.command.AbstractTransactionalCommand.doExecute(AbstractTransactionalCommand.java:247)
    at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
    at org.eclipse.emf.workspace.CompositeEMFOperation.doExecute(CompositeEMFOperation.java:217)
    at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
    at org.eclipse.papyrus.infra.gmfdiag.common.commands.CreateEditBasedElementCommand$1.doExecuteWithResult(CreateEditBasedElementCommand.java:331)
    at org.eclipse.gmf.runtime.emf.commands.core.command.AbstractTransactionalCommand.doExecute(AbstractTransactionalCommand.java:247)
    at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
    at org.eclipse.emf.workspace.CompositeEMFOperation.doExecute(CompositeEMFOperation.java:217)
    at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
    at org.eclipse.papyrus.infra.gmfdiag.common.commands.CreateEditBasedElementCommand.doExecuteWithResult(CreateEditBasedElementCommand.java:309)
    at org.eclipse.gmf.runtime.emf.commands.core.command.AbstractTransactionalCommand.doExecute(AbstractTransactionalCommand.java:247)
    at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
    at org.eclipse.gmf.runtime.diagram.ui.commands.SemanticCreateCommand.doExecuteWithResult(SemanticCreateCommand.java:91)
    at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
    at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
    at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
    at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
    at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
    at org.eclipse.gmf.runtime.common.core.command.CompositeCommand.doExecuteWithResult(CompositeCommand.java:403)
    at org.eclipse.gmf.runtime.common.core.command.AbstractCommand.execute(AbstractCommand.java:134)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
    ... 41 more

**Comment by bmaggi** [comment]
Hum, I don't get the exception.

Some questions:
What is your Papyrus base ?(mine Papyrus Eclipse Neon RC2)
Did you install UML2 feature?
What is supposed to do the BugzillaAdvice?
What is a Bugzilla in your DSML?

**Comment by patnan** [comment]
I'm using an Oomph setup including these (and other :) features.
- Papyrus UML   2.0.0.201605310148  org.eclipse.papyrus.sdk.feature.feature.group
- UML2 Extender SDK 5.2.0.v20160516-0939    org.eclipse.uml2.sdk.feature.group  

The Bugzilla is a class stereotyped as a WorkPart with the stereotype property type set to Bugzilla. 

The BugzillaAdvice sets the stereotype and stereotype properties. 

Prior to this commit it worked fine, now it isn't able to set the stereotype I realized when I debugged a bit. The Element.applySterotype() returns an EObject which is of type WorkPartImpl. However since I new to static generated profiles and stereotypes I'm not able to judge it that instance is ok or not.

Also, I'm not either able to set it manually using the properties view.

I'm been trying to compare the two latest commits (where the issue appeared) and I can't find the problem. The biggest change seems to be in the profile file itself but I fail to see the actual change.

**Comment by patnan** [comment]
Checking out fix #5 Generatingthe static profile it works.

I noticed when I debugged that the element.applyStereotype() then returns an object of org.eclipse.emf.ecore.impl.DynamicEObjectImpl rather than a WorkPartImpl. Don't know what that means...

**Comment by patnan** [comment]
Another thing, when opening a profiled model that was created with #5 using the failing latest commit Papyrus wants me to reapply the profile which has version 0.0.0 (before it was 0.0.1)
profile_fail

**Pull request merged**
